language: python

matrix:
  include:
    - os: linux
      dist: bionic

before_install:
  # LINUX
  - apt update
  - apt install -y python3 python3-pip
  - pip install -r requirements.txt
script:
  - python3 run_tests.py

cache:
  directories:
  - $HOME/travis_cache
